# Generated by Django 2.2.12 on 2020-04-06 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/recipes/'),
        ),
    ]
