# Generated by Django 2.2.12 on 2020-04-06 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='profile_picture',
            new_name='recipe_image',
        ),
    ]
