# Generated by Django 2.0.2 on 2020-03-30 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20200330_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='created_date',
            field=models.DateField(verbose_name='created_date'),
        ),
    ]
