# Generated by Django 2.2.11 on 2020-03-31 15:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_info', models.TextField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(1)])),
                ('profile_picture', models.ImageField(blank=True, default='images/default-profile.png', null=True, upload_to='images/')),
                ('created_date', models.DateTimeField(verbose_name='created_date')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
