# Generated by Django 2.2.12 on 2020-04-06 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='images/profiles/default-profile.png', null=True, upload_to='images/profiles/'),
        ),
    ]
