# Generated by Django 2.2.8 on 2020-02-10 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profile_picture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='files.ImageFile'),
        ),
    ]
