# Generated by Django 2.0.2 on 2020-02-28 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200210_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profile_picture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='files.ImageFile'),
        ),
    ]
