# Generated by Django 2.0.2 on 2020-03-02 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200228_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='full_name',
        ),
    ]
