# Generated by Django 2.0.2 on 2020-03-02 12:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0001_initial'),
        ('users', '0005_remove_author_full_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='Profile',
        ),
    ]
