# Generated by Django 2.0.2 on 2020-03-02 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200302_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.FileField(null=True, upload_to='images'),
        ),
    ]
