# Generated by Django 2.0.2 on 2020-03-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200302_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='images/default-profile.png', null=True, upload_to='images/'),
        ),
    ]
